help:		##Print this line
	fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep |sed -e 's/##//'

Frontend:	## Install Frontend Component
	@echo Installing Frontend

Catalogue:	## Install Catalogue Component
	@echo Installing Catalogue

Cart:		## Install Cart Component
	@echo Installing Cart

User:		## Install User Component
	@echo Installing User

Shipping:	## Install Shipping Component
	@echo Installing Shipping

Payment:	## Install Payment Component
	@echo Installing Payment

MongodB:	## Install MongodB Component
	@echo Installing MongodB

Redis:		## Install Redis Component
	@echo Installing Redis

MySQL:		## Install MySQL Component
	@echo Installing MySQL

Rabbitmq:	## Install Rabbitmq Component
	@echo Installing Rabbitmq