frontend:
	@echo Installing Frontend

Catalogue:
	@echo Installing Catalogue

Cart:
	@echo Installing Cart

User:
	@echo Installing User

Shipping:
	@echo Installing Shipping

Payment:
	@echo Installing Payment

MongodB:
	@echo Installing MongodB

Redis:
	@echo Installing Redis

MySQL:
	@echo Installing MySQL

Rabbitmq:
	@echo Installing Rabbitmq